name: type_safe_wait_on_futures
description: Type safe wait on futures, as an alternative to the non-type-safe Future.wait().
version: 0.2.0
repository: https://github.com/martinsellergren/type_safe_wait_on_futures

environment:
  sdk: ^3.4.3

dev_dependencies:
  lints: ^3.0.0
